/**
 * DiagramFile — the JSON document format for a single-line diagram.
 *
 * Two-layer separation:
 *   - Topology: `elements` + `connections`   (what is connected to what)
 *   - Diagram:  `layout`   + `routes`        (where to draw it)
 *
 * Connectivity is expressed by union-find over `connections` — authors and
 * LLMs do not need to invent ConnectivityNode IDs. The editor materializes
 * nodes at compile time. See `docs/data-model.md`.
 */

import type { LibraryEntry } from './library';

/** Document schema version. Bump on breaking changes. */
export type DiagramVersion = '1';

/** Human-readable element identifier, unique within a diagram. e.g. "QF1". */
export type ElementId = string;

/** Pin name as defined by the element's `LibraryEntry.terminals[].id`. */
export type PinName = string;

/** ConnectivityNode identifier, generated by the compiler unless named. */
export type NodeId = string;

/**
 * Terminal address: "<elementId>.<pinName>".
 * Multiple `connections` referencing the same terminal merge into one node.
 */
export type TerminalRef = `${ElementId}.${PinName}`;

/** Root document. Single source of truth, written to/read from JSON. */
export interface DiagramFile {
  version: DiagramVersion;
  meta?: DiagramMeta;
  elements: Element[];
  connections?: Connection[];
  /** Sparse: missing keys → auto-layout. */
  layout?: Record<ElementId, Placement>;
  /** Sparse: missing keys → auto-route. */
  routes?: Record<NodeId, Route>;
  /** Free-floating text notes the user dropped on the canvas. Independent
   *  of `elements` — annotations have no terminals and no connectivity. */
  annotations?: TextAnnotation[];
}

/** Identifier for a free text annotation; minted by `newAnnotationId`. */
export type AnnotationId = string;

/**
 * A free-floating text note placed on the canvas. Position is the text's
 * top-left in canvas coordinates. Empty `text` is treated as deleted by the
 * editor — the renderer does not paint it and the property panel offers no
 * controls for one.
 */
export interface TextAnnotation {
  id: AnnotationId;
  at: [number, number];
  text: string;
  /** Optional override for the rendered font size in canvas units. */
  fontSize?: number;
}

export interface DiagramMeta {
  title?: string;
  description?: string;
  author?: string;
  /** ISO 8601 timestamp. */
  createdAt?: string;
  /** ISO 8601 timestamp. */
  updatedAt?: string;
  /** Structural-label visibility on the canvas. Default `'all'`.
   *  - `'off'`: hide all labels.
   *  - `'id'`: only the element's name/ID.
   *  - `'all'`: ID plus every param flagged `showOnCanvas` in the library. */
  labelMode?: LabelMode;
}

export type LabelMode = 'off' | 'id' | 'all';

/** Permitted value types for `Element.params`. */
export type ParamValue = number | string | boolean;

/**
 * A device instance on the diagram.
 *
 * `kind` references `LibraryEntry.id` from the element library. The library
 * defines the SVG, the available pin names, and the default parameters; this
 * type is intentionally open so the library can grow without TS changes.
 */
export interface Element {
  id: ElementId;
  /** Must equal a `LibraryEntry.id`. See `src/element-library/*.json`. */
  kind: LibraryEntry['id'] | (string & {});
  /** Display name; defaults to `id` when omitted. */
  name?: string;
  /** Free-form annotation; preserved through round-trips, useful as LLM context. */
  note?: string;
  /** Only fields that override library defaults need to appear. */
  params?: Record<string, ParamValue>;

  /**
   * Runtime state. Allowed keys are declared by the kind's
   * `LibraryEntry.state` (e.g. breaker → `{ open }`, fuse → `{ blown }`).
   * Validated against the library at compile time, not by TS.
   */
  state?: Record<string, ParamValue>;

  // ---- Bus convenience ----------------------------------------------------

  /**
   * Bus tap list — equivalent to writing one `Connection` per entry that
   * pairs the bus with the listed terminal. Order also hints visual order
   * along the bus for auto-layout. Only valid on bus-like kinds.
   */
  tap?: TerminalRef[];
}

/**
 * One ConnectivityNode contribution. All listed terminals are electrically
 * the same node; nodes sharing terminals merge transitively.
 *
 * Use the array form by default. Use `NamedConnection` only when the node
 * itself needs a stable identity (so `routes[nodeId]` or annotations can
 * reference it).
 */
export type Connection = TerminalRef[] | NamedConnection;

export interface NamedConnection {
  node?: NodeId;
  name?: string;
  terminals: TerminalRef[];
}

/** Placement on the canvas. Omitted fields default to 0 / false. */
export interface Placement {
  /** Hotspot position in canvas coordinates. */
  at: [number, number];
  /** 90° step rotation. */
  rot?: 0 | 90 | 180 | 270;
  mirror?: boolean;
  /** Length along the stretch axis; only valid for stretchable kinds. */
  span?: number;
}

/** Visual polyline path for one ConnectivityNode. */
export interface Route {
  path: [number, number][];
  /** True = user-edited; serializer must preserve it verbatim. */
  manual?: boolean;
}
